In [1]:
import numpy as np
a=np.array([5,6,9])
a[0]


5

In [2]:
a[1]

6

In [3]:
a=np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [4]:
a=np.array([5,6,9])
a.ndim

1

In [6]:
a.itemsize

4

In [8]:
a.dtype

dtype('int32')

In [9]:
a=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
a.itemsize

8

In [10]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [11]:
a.size

6

In [12]:
a.shape

(3, 2)

In [54]:
a=np.array([[1,2],[3,4],[5,6]],dtype=complex)
a.itemsize

16

In [14]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
l=range(5)
l

range(0, 5)

In [17]:
l[0]

0

In [18]:
l[1]

1

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [20]:
np.arange(1,5,2)

array([1, 3])

In [38]:
a.reshape(2,3)

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

In [26]:
a.reshape(6,1)

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j],
       [4.+0.j],
       [5.+0.j],
       [6.+0.j]])

In [27]:
a.ravel()

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [28]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [31]:
a.min()

(1+0j)

In [32]:
a.max()

(6+0j)

In [33]:
a.sum()

(21+0j)

In [34]:
a.sum(axis=0)

array([ 9.+0.j, 12.+0.j])

In [35]:
a.sum(axis=1)

array([ 3.+0.j,  7.+0.j, 11.+0.j])

In [40]:
np.sqrt(a)

array([[1.        +0.j, 1.41421356+0.j],
       [1.73205081+0.j, 2.        +0.j],
       [2.23606798+0.j, 2.44948974+0.j]])

In [41]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [42]:
np.std(a)

1.707825127659933

In [57]:
import numpy as np
a=np.array([5,6,9])
a


array([5, 6, 9])

In [45]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [58]:
a

array([5, 6, 9])

In [47]:
b

array([[5, 6],
       [7, 8]])

In [59]:
a+b

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [60]:
a-b

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 